<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Digression II: Survival analysis with R | Everyday-R: Practical R for Data Science</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Digression II: Survival analysis with R | Everyday-R: Practical R for Data Science" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Digression II: Survival analysis with R | Everyday-R: Practical R for Data Science" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="by Brian Jungmin Park" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="digression-i-gradient-descent-with-r.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Everyday-R by snowoflondon</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#preface"><i class="fa fa-check"></i><b>1.1</b> Preface</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#r-syntax-in-this-book"><i class="fa fa-check"></i><b>1.2</b> R syntax in this book</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#r-packages-commonly-used-in-this-book"><i class="fa fa-check"></i><b>1.3</b> R packages commonly used in this book</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#installing-r-packages"><i class="fa fa-check"></i><b>1.4</b> Installing R packages</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#code-availability"><i class="fa fa-check"></i><b>1.5</b> Code availability</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#website-hosting"><i class="fa fa-check"></i><b>1.6</b> Website hosting</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html"><i class="fa fa-check"></i><b>2</b> Everyday data wrangling</a>
<ul>
<li class="chapter" data-level="2.1" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#renaming-column-headers"><i class="fa fa-check"></i><b>2.1</b> Renaming column headers</a></li>
<li class="chapter" data-level="2.2" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#grouped-operations"><i class="fa fa-check"></i><b>2.2</b> Grouped operations</a></li>
<li class="chapter" data-level="2.3" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#data-transformation"><i class="fa fa-check"></i><b>2.3</b> Data transformation</a></li>
<li class="chapter" data-level="2.4" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#joining-and-separating-character-columns"><i class="fa fa-check"></i><b>2.4</b> Joining and separating character columns</a></li>
<li class="chapter" data-level="2.5" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#filtering-rows"><i class="fa fa-check"></i><b>2.5</b> Filtering rows</a></li>
<li class="chapter" data-level="2.6" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#subsetting-columns-based-on-strings"><i class="fa fa-check"></i><b>2.6</b> Subsetting columns based on strings</a></li>
<li class="chapter" data-level="2.7" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#long-and-wide-data-formats"><i class="fa fa-check"></i><b>2.7</b> Long and wide data formats</a></li>
<li class="chapter" data-level="2.8" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#trimming-strings"><i class="fa fa-check"></i><b>2.8</b> Trimming strings</a></li>
<li class="chapter" data-level="2.9" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#iterating-over-list-of-dataframes"><i class="fa fa-check"></i><b>2.9</b> Iterating over list of dataframes</a></li>
<li class="chapter" data-level="2.10" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#rowwise-operations"><i class="fa fa-check"></i><b>2.10</b> Rowwise operations</a></li>
<li class="chapter" data-level="2.11" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#conditional-transformation"><i class="fa fa-check"></i><b>2.11</b> Conditional transformation</a></li>
<li class="chapter" data-level="2.12" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#missing-values"><i class="fa fa-check"></i><b>2.12</b> Missing values</a></li>
<li class="chapter" data-level="2.13" data-path="everyday-data-wrangling.html"><a href="everyday-data-wrangling.html#joining-dataframes"><i class="fa fa-check"></i><b>2.13</b> Joining dataframes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="everyday-iterations.html"><a href="everyday-iterations.html"><i class="fa fa-check"></i><b>3</b> Everyday iterations</a>
<ul>
<li class="chapter" data-level="3.1" data-path="everyday-iterations.html"><a href="everyday-iterations.html#iterating-over-multiple-columns-using-apply-dplyr-and-purrr"><i class="fa fa-check"></i><b>3.1</b> Iterating over multiple columns using <code>apply()</code>, <code>dplyr</code>, and <code>purrr</code></a></li>
<li class="chapter" data-level="3.2" data-path="everyday-iterations.html"><a href="everyday-iterations.html#iterating-over-lists"><i class="fa fa-check"></i><b>3.2</b> Iterating over lists</a></li>
<li class="chapter" data-level="3.3" data-path="everyday-iterations.html"><a href="everyday-iterations.html#iterating-over-vectors"><i class="fa fa-check"></i><b>3.3</b> Iterating over vectors</a></li>
<li class="chapter" data-level="3.4" data-path="everyday-iterations.html"><a href="everyday-iterations.html#iterating-with-two-inputs"><i class="fa fa-check"></i><b>3.4</b> Iterating with two inputs</a></li>
<li class="chapter" data-level="3.5" data-path="everyday-iterations.html"><a href="everyday-iterations.html#iterating-over-indices-and-names"><i class="fa fa-check"></i><b>3.5</b> Iterating over indices and names</a></li>
<li class="chapter" data-level="3.6" data-path="everyday-iterations.html"><a href="everyday-iterations.html#handling-errors-within-purrr"><i class="fa fa-check"></i><b>3.6</b> Handling errors within <code>purrr</code></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="interlude-i-a-brief-glimpse-into-data.html"><a href="interlude-i-a-brief-glimpse-into-data.html"><i class="fa fa-check"></i><b>4</b> Interlude I: A brief glimpse into <code>data.table</code></a>
<ul>
<li class="chapter" data-level="4.1" data-path="interlude-i-a-brief-glimpse-into-data.html"><a href="interlude-i-a-brief-glimpse-into-data.html#data-wrangling-operations"><i class="fa fa-check"></i><b>4.1</b> Data wrangling operations</a></li>
<li class="chapter" data-level="4.2" data-path="interlude-i-a-brief-glimpse-into-data.html"><a href="interlude-i-a-brief-glimpse-into-data.html#sd-.sdcols-and"><i class="fa fa-check"></i><b>4.2</b> <code>.SD</code>, <code>.SDcols</code>, and <code>:=</code></a></li>
<li class="chapter" data-level="4.3" data-path="interlude-i-a-brief-glimpse-into-data.html"><a href="interlude-i-a-brief-glimpse-into-data.html#reshaping-data-using-melt-and-dcast"><i class="fa fa-check"></i><b>4.3</b> Reshaping data using <code>melt</code> and <code>dcast</code></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="everyday-exploratory-data-analysis.html"><a href="everyday-exploratory-data-analysis.html"><i class="fa fa-check"></i><b>5</b> Everyday exploratory data analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="everyday-exploratory-data-analysis.html"><a href="everyday-exploratory-data-analysis.html#workflow-1-continuous-data"><i class="fa fa-check"></i><b>5.1</b> Workflow 1: continuous data</a></li>
<li class="chapter" data-level="5.2" data-path="everyday-exploratory-data-analysis.html"><a href="everyday-exploratory-data-analysis.html#workflow-2-dates-and-ordinal-data"><i class="fa fa-check"></i><b>5.2</b> Workflow 2: dates and ordinal data</a></li>
<li class="chapter" data-level="5.3" data-path="everyday-exploratory-data-analysis.html"><a href="everyday-exploratory-data-analysis.html#visualization-of-clusters"><i class="fa fa-check"></i><b>5.3</b> Visualization of clusters</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html"><i class="fa fa-check"></i><b>6</b> Everyday ML: Classification</a>
<ul>
<li class="chapter" data-level="6.1" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#model-training-and-predictions"><i class="fa fa-check"></i><b>6.1</b> Model training and predictions</a></li>
<li class="chapter" data-level="6.2" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#feature-selection-using-univariate-filters"><i class="fa fa-check"></i><b>6.2</b> Feature selection using univariate filters</a></li>
<li class="chapter" data-level="6.3" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#feature-selection-using-recursive-feature-elimination"><i class="fa fa-check"></i><b>6.3</b> Feature selection using recursive feature elimination</a></li>
<li class="chapter" data-level="6.4" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#feature-selection-for-correlated-and-low-variance-predictors"><i class="fa fa-check"></i><b>6.4</b> Feature selection for correlated and low-variance predictors</a></li>
<li class="chapter" data-level="6.5" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#hyperparameter-tuning"><i class="fa fa-check"></i><b>6.5</b> Hyperparameter tuning</a></li>
<li class="chapter" data-level="6.6" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#roc-and-precision-recall-curves"><i class="fa fa-check"></i><b>6.6</b> ROC and precision-recall curves</a></li>
<li class="chapter" data-level="6.7" data-path="everyday-ml-classification.html"><a href="everyday-ml-classification.html#model-comparisons"><i class="fa fa-check"></i><b>6.7</b> Model comparisons</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="everyday-ml-regression.html"><a href="everyday-ml-regression.html"><i class="fa fa-check"></i><b>7</b> Everyday ML: Regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="everyday-ml-regression.html"><a href="everyday-ml-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>7.1</b> Simple linear regression</a></li>
<li class="chapter" data-level="7.2" data-path="everyday-ml-regression.html"><a href="everyday-ml-regression.html#using-regression-for-prediction"><i class="fa fa-check"></i><b>7.2</b> Using regression for prediction</a></li>
<li class="chapter" data-level="7.3" data-path="everyday-ml-regression.html"><a href="everyday-ml-regression.html#categorical-predictors-and-factor-encoding"><i class="fa fa-check"></i><b>7.3</b> Categorical predictors and factor encoding</a></li>
<li class="chapter" data-level="7.4" data-path="everyday-ml-regression.html"><a href="everyday-ml-regression.html#elastic-net-regression"><i class="fa fa-check"></i><b>7.4</b> Elastic net regression</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="digression-i-gradient-descent-with-r.html"><a href="digression-i-gradient-descent-with-r.html"><i class="fa fa-check"></i><b>8</b> Digression I: Gradient descent with R</a></li>
<li class="chapter" data-level="9" data-path="digression-ii-survival-analysis-with-r.html"><a href="digression-ii-survival-analysis-with-r.html"><i class="fa fa-check"></i><b>9</b> Digression II: Survival analysis with R</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Everyday-R: Practical R for Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="digression-ii-survival-analysis-with-r" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Digression II: Survival analysis with R<a href="digression-ii-survival-analysis-with-r.html#digression-ii-survival-analysis-with-r" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>One of the main advantages in using R is the abundance of maintained packages for a wide variety of statistical applications. An example of a commonly used statistical concept is survival analysis, also known as time-to-event analysis. Survival analysis is used to find the time until a specified event occurs - in most cases, this event is an outcome or an endpoint for a study. This outcome could be death of a patient or a disease re-occurrence (often used in clinical studies to study the relationship between patient survival and patient striations) or something mundane such as customer churning or a failure of a mechanical system. In R, such analysis can be handled trivially using syntax already familiar to us.</p>
<p>There are two functions critical to survival analysis: the survival function <span class="math inline">\(S(t)\)</span> and the hazard function <span class="math inline">\(h(t)\)</span> - both a function of time <span class="math inline">\(t\)</span>. The survival function describes the probability of surviving beyond time <span class="math inline">\(t\)</span> without the event occurring. It describes the proportion of the sample which has not experienced the event up until <span class="math inline">\(t\)</span>. The hazard function describes the rate at which events occur at time <span class="math inline">\(t\)</span>, given that the sample has survived up until that time. Thus, a higher value of this rate denotes higher risk.</p>
<p>The Kaplan-Meier estimator is used to estimate the survival function <span class="math inline">\(S(t)\)</span> given censored data. In this case, a data point is said to be censored if the sample (i.e., individual) does not experience the event during the study period. The Kaplan-Meier method is non-parametric, which means it does not make any assumptions about the distribution of the survival times. It also does not quantify the effect size (i.e., difference in risk between sample groups) but instead outputs the probability of survival at given time points.</p>
<p><span class="math inline">\(\hat{S}(t)=\prod_{i:t_{i}\le t} (1-\frac{d_{i}}{n_{i}})\)</span></p>
<p>Here, <span class="math inline">\(\hat{S}(t)\)</span> describes the probability of survival at <span class="math inline">\(t\)</span>, <span class="math inline">\(t\)</span> is the time of interest, <span class="math inline">\(t_{i}\)</span> is the times of event occurrences, <span class="math inline">\(d_{i}\)</span> is the number of observed events, and <span class="math inline">\(n_{i}\)</span> is the number of individuals at risk before <span class="math inline">\(t_{i}\)</span>. The product is evaluated over all event times <span class="math inline">\(t_{i}\)</span> less than equal to the time point of interest <span class="math inline">\(t\)</span>. For each <span class="math inline">\(t_{i}\)</span> then, <span class="math inline">\((1-\frac{d_{i}}{n_{i}})\)</span> denotes the probability of surviving beyond <span class="math inline">\(t_{i}\)</span>.</p>
<p>Often, we frame our hypothesis to test whether there is a difference between two groups of individuals with respect to their survival probability. For example, we might be interested in whether, given patients enrolled in chemotherapy, men and women have different survival outcomes. Two survival functions can be subject to the log-rank test to compare the distributions:</p>
<p><span class="math inline">\(\chi^{2}=\sum_{i}^{n}\frac{(O_{i}-E_{i})^{2}}{E_{i}}\)</span></p>
<p>Above, <span class="math inline">\(O_{i}\)</span> is the number of observed events in group <span class="math inline">\(i\)</span>, while <span class="math inline">\(E_{i}\)</span> is the number of expected events in <span class="math inline">\(i\)</span>. <span class="math inline">\(n\)</span> is the number of groups being compared. The <span class="math inline">\(E_{i}\)</span> term here can be calculated based on the Kaplan-Meier probabilities and the total number of observed events across the groups. The obtained log-rank test statistic is compared against the <span class="math inline">\(\chi^{2}\)</span> distribution for statistical inference.</p>
<p>In R, the workhorse of survival analysis is the aptly named package <code>survival</code> and <code>survminer</code>.</p>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="digression-ii-survival-analysis-with-r.html#cb499-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb499-2"><a href="digression-ii-survival-analysis-with-r.html#cb499-2" tabindex="-1"></a><span class="fu">library</span>(survival)</span>
<span id="cb499-3"><a href="digression-ii-survival-analysis-with-r.html#cb499-3" tabindex="-1"></a><span class="fu">library</span>(survminer)</span>
<span id="cb499-4"><a href="digression-ii-survival-analysis-with-r.html#cb499-4" tabindex="-1"></a></span>
<span id="cb499-5"><a href="digression-ii-survival-analysis-with-r.html#cb499-5" tabindex="-1"></a>df <span class="ot">&lt;-</span> survival<span class="sc">::</span>ovarian <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb499-6"><a href="digression-ii-survival-analysis-with-r.html#cb499-6" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 26
## Columns: 6
## $ futime   &lt;dbl&gt; 59, 115, 156, 421, 431, 448, 464, 475, 477, …
## $ fustat   &lt;dbl&gt; 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,…
## $ age      &lt;dbl&gt; 72.3315, 74.4932, 66.4658, 53.3644, 50.3397,…
## $ resid.ds &lt;dbl&gt; 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2, 1,…
## $ rx       &lt;dbl&gt; 1, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 1,…
## $ ecog.ps  &lt;dbl&gt; 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1,…</code></pre>
<p>I loaded the ovarian cancer dataset from the <code>survival</code> package. Here, we can striate the patients into two groups based on the <code>rx</code> column, which describes two different treatment regimen. The censor status as a binary variable is located in the <code>fustat</code> column, where <code>0</code> indicates censored, and <code>1</code> indicates death.</p>
<p>The Kaplan-Meier estimator is fit using <code>survfit()</code> on a survival object created by <code>Surv()</code>. Here, standard formula notation applies as we saw before.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="digression-ii-survival-analysis-with-r.html#cb501-1" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(futime, fustat) <span class="sc">~</span> rx, <span class="at">data =</span> df)</span>
<span id="cb501-2"><a href="digression-ii-survival-analysis-with-r.html#cb501-2" tabindex="-1"></a>s</span></code></pre></div>
<pre><code>## Call: survfit(formula = Surv(futime, fustat) ~ rx, data = df)
## 
##       n events median 0.95LCL 0.95UCL
## rx=1 13      7    638     268      NA
## rx=2 13      5     NA     475      NA</code></pre>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="digression-ii-survival-analysis-with-r.html#cb503-1" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb503-2"><a href="digression-ii-survival-analysis-with-r.html#cb503-2" tabindex="-1"></a><span class="fu">tidy</span>(s)</span></code></pre></div>
<pre><code>## # A tibble: 26 × 9
##     time n.risk n.event n.censor estimate std.error conf.high
##    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1    59     13       1        0    0.923    0.0801     1    
##  2   115     12       1        0    0.846    0.118      1    
##  3   156     11       1        0    0.769    0.152      1    
##  4   268     10       1        0    0.692    0.185      0.995
##  5   329      9       1        0    0.615    0.219      0.946
##  6   431      8       1        0    0.538    0.257      0.891
##  7   448      7       0        1    0.538    0.257      0.891
##  8   477      6       0        1    0.538    0.257      0.891
##  9   638      5       1        0    0.431    0.340      0.840
## 10   803      4       0        1    0.431    0.340      0.840
## # ℹ 16 more rows
## # ℹ 2 more variables: conf.low &lt;dbl&gt;, strata &lt;chr&gt;</code></pre>
<p>The survival plots are then drawn:</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="digression-ii-survival-analysis-with-r.html#cb505-1" tabindex="-1"></a><span class="fu">ggsurvplot</span>(s, <span class="at">ggtheme =</span> <span class="fu">theme_survminer</span>(),</span>
<span id="cb505-2"><a href="digression-ii-survival-analysis-with-r.html#cb505-2" tabindex="-1"></a>           <span class="at">risk.table =</span> <span class="st">&#39;abs_pct&#39;</span>, <span class="at">pval =</span> <span class="cn">TRUE</span>,</span>
<span id="cb505-3"><a href="digression-ii-survival-analysis-with-r.html#cb505-3" tabindex="-1"></a>           <span class="at">risk.table.col =</span> <span class="st">&#39;strata&#39;</span>,</span>
<span id="cb505-4"><a href="digression-ii-survival-analysis-with-r.html#cb505-4" tabindex="-1"></a>           <span class="at">palette =</span> <span class="fu">c</span>(<span class="st">&quot;#a6f5c5&quot;</span>, <span class="st">&quot;#9d95bc&quot;</span>),</span>
<span id="cb505-5"><a href="digression-ii-survival-analysis-with-r.html#cb505-5" tabindex="-1"></a>           <span class="at">surv.median.line =</span> <span class="st">&#39;hv&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-282-1.png" width="672" /></p>
<p>Here, the p-value (<span class="math inline">\(p=0.3\)</span>) indicated on the figure is the p-value obtained from the log-rank test comparing the two groups. We can also extract this value by:</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="digression-ii-survival-analysis-with-r.html#cb506-1" tabindex="-1"></a><span class="fu">surv_pvalue</span>(s)</span></code></pre></div>
<pre><code>##   variable      pval   method pval.txt
## 1       rx 0.3025911 Log-rank  p = 0.3</code></pre>
<p>The log-rank test and its associated values (such as the expected number of events) can formally be run using <code>survdiff()</code> as well:</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="digression-ii-survival-analysis-with-r.html#cb508-1" tabindex="-1"></a><span class="fu">survdiff</span>(<span class="fu">Surv</span>(futime, fustat) <span class="sc">~</span> rx, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## Call:
## survdiff(formula = Surv(futime, fustat) ~ rx, data = df)
## 
##       N Observed Expected (O-E)^2/E (O-E)^2/V
## rx=1 13        7     5.23     0.596      1.06
## rx=2 13        5     6.77     0.461      1.06
## 
##  Chisq= 1.1  on 1 degrees of freedom, p= 0.3</code></pre>
<p>In order to quantify the difference in risk between the two groups, we use the hazard function.</p>
<p><span class="math inline">\(h_{i}(t)=h_{0}(t)e^{\sum_{i}^{n}\beta x}\)</span></p>
<p>Here, <span class="math inline">\(h_{i}(t)\)</span> denotes the hazard function for group <span class="math inline">\(i\)</span>, which is a function of time <span class="math inline">\(t\)</span>. It is then the exponential of the coefficient <span class="math inline">\(\beta\)</span> obtained from model fitting which describes the effect size of the hazard function. The ratio between two hazard functions (i.e., between individuals or groups) then describes the relative difference in risk.</p>
<p>Therefore, it is evident that unlike the Kaplan-Meier estimator, hazard models output a list of coefficients for each covariate along with their p-values. This means that we are able to identify the magnitude and the direction of the association between each predictor variable and the hazard of experiencing the event.</p>
<p>Formally, the hazards regression model is fit in R using <code>coxph()</code> (stands for Cox proportional hazards model):</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb510-1"><a href="digression-ii-survival-analysis-with-r.html#cb510-1" tabindex="-1"></a>cox <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(futime, fustat) <span class="sc">~</span> rx, </span>
<span id="cb510-2"><a href="digression-ii-survival-analysis-with-r.html#cb510-2" tabindex="-1"></a>             <span class="at">data =</span> df, <span class="at">ties =</span> <span class="st">&#39;exact&#39;</span>)</span>
<span id="cb510-3"><a href="digression-ii-survival-analysis-with-r.html#cb510-3" tabindex="-1"></a><span class="fu">summary</span>(cox)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(futime, fustat) ~ rx, data = df, ties = &quot;exact&quot;)
## 
##   n= 26, number of events= 12 
## 
##       coef exp(coef) se(coef)      z Pr(&gt;|z|)
## rx -0.5964    0.5508   0.5870 -1.016     0.31
## 
##    exp(coef) exp(-coef) lower .95 upper .95
## rx    0.5508      1.816    0.1743      1.74
## 
## Concordance= 0.608  (se = 0.07 )
## Likelihood ratio test= 1.05  on 1 df,   p=0.3
## Wald test            = 1.03  on 1 df,   p=0.3
## Score (logrank) test = 1.06  on 1 df,   p=0.3</code></pre>
<p>Firstly, look at the last portion of the <code>summary()</code> output: the log-rank test is included in the model output as a test for overall difference in the groups. The p-value here should equal to the p-value we obtained previously for the log-rank test:</p>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb512-1"><a href="digression-ii-survival-analysis-with-r.html#cb512-1" tabindex="-1"></a><span class="fu">summary</span>(cox)<span class="sc">$</span>sctest</span></code></pre></div>
<pre><code>##      test        df    pvalue 
## 1.0627399 1.0000000 0.3025911</code></pre>
<p>Going back to the <code>summary()</code> output, the <code>coef</code> given equals the regression model coefficient <span class="math inline">\(\beta\)</span>. Here, since there are two groups, the first group (i.e., <code>rx=1</code>) is used as the reference. Here, the <code>coef</code> value of <code>-0.5964</code> suggests that the <code>rx=2</code> group have lower risk than the other, though obviously the result is not statistically significant. The effect size, or the hazard ratio then, is the exponential of this value, which is also given in the <code>summary()</code> output as <code>0.5508</code>. This result suggests that the second group havs less risk of event than the other by a factor of 0.5508, or roughly 45%, at p-value of 0.31 (i.e., not significant).</p>
<p>The advantage of the hazard regression model is the ability to fit multiple predictors. This allows us to account for correlation between the predictor variables and identify potential associations.</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb514-1"><a href="digression-ii-survival-analysis-with-r.html#cb514-1" tabindex="-1"></a>cox2 <span class="ot">&lt;-</span> <span class="fu">coxph</span>(<span class="fu">Surv</span>(futime, fustat) <span class="sc">~</span> rx <span class="sc">+</span> age <span class="sc">+</span> ecog.ps,</span>
<span id="cb514-2"><a href="digression-ii-survival-analysis-with-r.html#cb514-2" tabindex="-1"></a>              <span class="at">data =</span> df, <span class="at">ties =</span> <span class="st">&#39;exact&#39;</span>)</span></code></pre></div>
<p>The log-rank test returns a p-value of <code>3.14e-04</code>, suggesting a difference between the groups.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="digression-ii-survival-analysis-with-r.html#cb515-1" tabindex="-1"></a><span class="fu">summary</span>(cox2)<span class="sc">$</span>sctest</span></code></pre></div>
<pre><code>##         test           df       pvalue 
## 1.870381e+01 3.000000e+00 3.147869e-04</code></pre>
<p>The <code>summary()</code> output on the multivariate model shows that there could be an association between patients’ age and hazard risk (<span class="math inline">\(\alpha &lt; .05\)</span>):</p>
<div class="sourceCode" id="cb517"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb517-1"><a href="digression-ii-survival-analysis-with-r.html#cb517-1" tabindex="-1"></a><span class="fu">summary</span>(cox2)</span></code></pre></div>
<pre><code>## Call:
## coxph(formula = Surv(futime, fustat) ~ rx + age + ecog.ps, data = df, 
##     ties = &quot;exact&quot;)
## 
##   n= 26, number of events= 12 
## 
##            coef exp(coef) se(coef)      z Pr(&gt;|z|)   
## rx      -0.8146    0.4428   0.6342 -1.285   0.1990   
## age      0.1470    1.1583   0.0463  3.175   0.0015 **
## ecog.ps  0.1032    1.1087   0.6064  0.170   0.8649   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
##         exp(coef) exp(-coef) lower .95 upper .95
## rx         0.4428     2.2582    0.1278     1.535
## age        1.1583     0.8633    1.0579     1.268
## ecog.ps    1.1087     0.9020    0.3378     3.639
## 
## Concordance= 0.798  (se = 0.078 )
## Likelihood ratio test= 15.92  on 3 df,   p=0.001
## Wald test            = 13.32  on 3 df,   p=0.004
## Score (logrank) test = 18.7  on 3 df,   p=3e-04</code></pre>
<p>A useful visualization to depict the respective hazard ratios is a linerange plot. For that we first need to do a bit of <code>dplyr</code> operations to obtain the confidence intervals and the hazard ratios.</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb519-1"><a href="digression-ii-survival-analysis-with-r.html#cb519-1" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="fu">tidy</span>(cox2)</span>
<span id="cb519-2"><a href="digression-ii-survival-analysis-with-r.html#cb519-2" tabindex="-1"></a>c <span class="ot">&lt;-</span> c <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">upper =</span> estimate<span class="fl">+1.96</span><span class="sc">*</span>std.error,</span>
<span id="cb519-3"><a href="digression-ii-survival-analysis-with-r.html#cb519-3" tabindex="-1"></a>                  <span class="at">lower =</span> estimate<span class="fl">-1.96</span><span class="sc">*</span>std.error)</span>
<span id="cb519-4"><a href="digression-ii-survival-analysis-with-r.html#cb519-4" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&#39;estimate&#39;</span>, <span class="st">&#39;upper&#39;</span>, <span class="st">&#39;lower&#39;</span>)</span>
<span id="cb519-5"><a href="digression-ii-survival-analysis-with-r.html#cb519-5" tabindex="-1"></a>c <span class="ot">&lt;-</span> c <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(r), exp))</span>
<span id="cb519-6"><a href="digression-ii-survival-analysis-with-r.html#cb519-6" tabindex="-1"></a></span>
<span id="cb519-7"><a href="digression-ii-survival-analysis-with-r.html#cb519-7" tabindex="-1"></a><span class="fu">ggplot</span>(c, <span class="fu">aes</span>(<span class="at">x =</span> estimate, <span class="at">y =</span> term,</span>
<span id="cb519-8"><a href="digression-ii-survival-analysis-with-r.html#cb519-8" tabindex="-1"></a>               <span class="at">color =</span> estimate<span class="sc">&gt;</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb519-9"><a href="digression-ii-survival-analysis-with-r.html#cb519-9" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">color =</span> <span class="st">&#39;gray&#39;</span>) <span class="sc">+</span></span>
<span id="cb519-10"><a href="digression-ii-survival-analysis-with-r.html#cb519-10" tabindex="-1"></a>  <span class="fu">geom_linerange</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lower, <span class="at">xmax =</span> upper),</span>
<span id="cb519-11"><a href="digression-ii-survival-analysis-with-r.html#cb519-11" tabindex="-1"></a>                 <span class="at">linewidth =</span> <span class="fl">1.5</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb519-12"><a href="digression-ii-survival-analysis-with-r.html#cb519-12" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span> <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb519-13"><a href="digression-ii-survival-analysis-with-r.html#cb519-13" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&#39;green&#39;</span>, <span class="st">&#39;red&#39;</span>),</span>
<span id="cb519-14"><a href="digression-ii-survival-analysis-with-r.html#cb519-14" tabindex="-1"></a>                     <span class="at">guide =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span></span>
<span id="cb519-15"><a href="digression-ii-survival-analysis-with-r.html#cb519-15" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">18</span>),</span>
<span id="cb519-16"><a href="digression-ii-survival-analysis-with-r.html#cb519-16" tabindex="-1"></a>        <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>)) <span class="sc">+</span></span>
<span id="cb519-17"><a href="digression-ii-survival-analysis-with-r.html#cb519-17" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&#39;&#39;</span>) <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&#39;HR estimate (95% C.I.)&#39;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-290-1.png" width="672" /></p>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="digression-i-gradient-descent-with-r.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/08-DigressionTwo.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
